<?php
$kur_ilkom_2012 = array(
    array(
        "KODE" => "UNI612101",
        "NAMA_MK" => "PENDIDIKAN AGAMA ISLAM",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612102",
        "NAMA_MK" => "PENDIDIKAN A. KRISTEN PROTESTAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612104",
        "NAMA_MK" => "PENDIDIKAN AGAMA HINDU",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612101",
        "NAMA_MK" => "ALGORITMA DAN PEMROGRAMAN (TEORI)",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612105",
        "NAMA_MK" => "PENDIDIKAN AGAMA BUDHA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612108",
        "NAMA_MK" => "BAHASA INGGRIS",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612109",
        "NAMA_MK" => "MATEMATIKA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612102",
        "NAMA_MK" => "ALGORITMA DAN PEMROGRAMAN (PRAKTEK)",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIP612101",
        "NAMA_MK" => "SAINS DASAR",
        "SKS" => "6",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612111",
        "NAMA_MK" => "STATISTIKA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612110",
        "NAMA_MK" => "LOGIKA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612103",
        "NAMA_MK" => "PENDIDIKAN AGAMA KATHOLIK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MPK612107",
        "NAMA_MK" => "KEWARGANEGARAAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT612219",
        "NAMA_MK" => "MATEMATIKA DISKRET",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612111",
        "NAMA_MK" => "PENGANTAR SISTEM INFORMASI",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612112",
        "NAMA_MK" => "ARSITEKTUR DAN ORGANISASI KOMPUTER",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612113",
        "NAMA_MK" => "PEMROGRAMAN TERSTRUKTUR (TEORI)",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612114",
        "NAMA_MK" => "PEMROGRAMAN TERSTRUKTUR (PRAKTIKUM)",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612106",
        "NAMA_MK" => "BAHASA INDONESIA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612115",
        "NAMA_MK" => "RANGKAIAN DIGITAL",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT612233",
        "NAMA_MK" => "PENGANTAR TEORI PELUANG",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT612104",
        "NAMA_MK" => "ALJABAR LINEAR ELEMENTER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "KOM612203",
        "NAMA_MK" => "SISTEM OPERASI (TEORI)",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "KOM612205",
        "NAMA_MK" => "PEMROGRAMAN BERORIENTASI OBYEK (TEORI",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "KOM612206",
        "NAMA_MK" => "PEMROGRAMAN BERORIENTASI OBYEK (PRAKTIKU",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612208",
        "NAMA_MK" => "KOMUNIKASI DATA DAN JARINGAN KOMPUTER PR",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612209",
        "NAMA_MK" => "BAHASA INGGRIS PROFESI",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612210",
        "NAMA_MK" => "PEMROGRAMAN INTERPRETER TEORI",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612211",
        "NAMA_MK" => "PEMROGRAMAN INTERPRETER PRAKTEK",
        "SKS" => "1",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612212",
        "NAMA_MK" => "PENGEMBANGAN APLIKASI XBASE",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612214",
        "NAMA_MK" => "GRAFIKA KOMPUTER",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612215",
        "NAMA_MK" => "GRAFIKA KOMPUTER PRAKTEK",
        "SKS" => "1",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "KOM612202",
        "NAMA_MK" => "STRUKTUR DATA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "KOM612204",
        "NAMA_MK" => "PRAKTIKUM SISTEM OPERASI",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612213",
        "NAMA_MK" => "PENGEMBANGAN APLIKASI XBASE PRAKTEK",
        "SKS" => "1",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "KOM612201",
        "NAMA_MK" => "REKAYASA PERANGKAT LUNAK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "KOM612207",
        "NAMA_MK" => "KOMUNIKASI DATA DAN JARINGAN KOMPUTER",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612225",
        "NAMA_MK" => "BASIS DATA P",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612227",
        "NAMA_MK" => "METODE NUMERIK",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612233",
        "NAMA_MK" => "SISTEM INFORMASI GEOGRAFIS",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612224",
        "NAMA_MK" => "BASIS DATA",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612226",
        "NAMA_MK" => "TEORI BAHASA DAN AUTOMATA",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612221",
        "NAMA_MK" => "ANALISIS ALGORITMA",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612229",
        "NAMA_MK" => "STUDI LAPANGAN",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612228",
        "NAMA_MK" => "HUKUM TELEMATIKA",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612222",
        "NAMA_MK" => "PEMROGRAMAN WEB",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612223",
        "NAMA_MK" => "PEMROGRAMAN WEB - P",
        "SKS" => "1",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612232",
        "NAMA_MK" => "REKAYASA APLIKASI BERGERAK",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612231",
        "NAMA_MK" => "MULTIMEDIA",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612309",
        "NAMA_MK" => "DATA WAREHOUSE",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612301",
        "NAMA_MK" => "ANALISIS DAN PEMODELAN SISTEM INFORMASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612310",
        "NAMA_MK" => "TATA KELOLA DAN AUDIT TEKNOLOGI INFORMASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612306",
        "NAMA_MK" => "MANAJEMEN PROYEK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612206",
        "NAMA_MK" => "KEWIRAUSAHAAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612305",
        "NAMA_MK" => "KECERDASAN BUATAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612304",
        "NAMA_MK" => "E-BISNIS",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612307",
        "NAMA_MK" => "PEMROSESAN BAHASA ALAMI",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612308",
        "NAMA_MK" => "MANAJEMEN PENGETAHUAN",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612327",
        "NAMA_MK" => "KOMPUTASI PARALEL",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612323",
        "NAMA_MK" => "KEAMANAN SISTEM INFORMASI",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612329",
        "NAMA_MK" => "TEMU KEMBALI SISTEM INFORMASI",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612303",
        "NAMA_MK" => "PRAKTEK KERJA LAPANG",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612324",
        "NAMA_MK" => "PROYEK KHUSUS",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612320",
        "NAMA_MK" => "EVOLUSI PROSES DAN KUALITAS PERANGKAT LUNAK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612325",
        "NAMA_MK" => "PENGUJIAN PERANGKAT LUNAK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612328",
        "NAMA_MK" => "OPERASI RISET",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612321",
        "NAMA_MK" => "INTERAKSI MANUSIA DAN KOMPUTER",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612326",
        "NAMA_MK" => "INFRASTRUKTUR TI DAN ARSITEKTUR ENTERPRISE",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "MIP612303",
        "NAMA_MK" => "ETIKA PROFESI",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "KOM612309",
        "NAMA_MK" => "DATA WAREHOUSE",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "UNI612402",
        "NAMA_MK" => "KKN TEMATIK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIP612103",
        "NAMA_MK" => "ETIKA PROFESI",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612401",
        "NAMA_MK" => "PENGENALAN POLA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612408",
        "NAMA_MK" => "KKN TEMATIK",
        "SKS" => "4",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "MIP612301",
        "NAMA_MK" => "METODOLOGI PENELITIAN",
        "SKS" => "4",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612404",
        "NAMA_MK" => "KAPITA SELEKTA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612407",
        "NAMA_MK" => "BIOINFORMATIKA",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612406",
        "NAMA_MK" => "PENGANTAR ROBOTIK",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612408",
        "NAMA_MK" => "MANAJEMEN RESIKO",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612409",
        "NAMA_MK" => "SISTEM PAKAR",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM612497",
        "NAMA_MK" => "SEMINAR USUL SKRIPSI",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612499",
        "NAMA_MK" => "SKRIPSI",
        "SKS" => "4",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM612498",
        "NAMA_MK" => "SEMINAR HASIL SKRIPSI",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
);
$kur_ilkom_2005 = array(
    array(
        "KODE" => "MPK106",
        "NAMA_MK" => "PANCASILA",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MPK101",
        "NAMA_MK" => "AGAMA ISLAM",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MPK103",
        "NAMA_MK" => "PENDIDIKAN AGAMA KATOLIK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MPK104",
        "NAMA_MK" => "PENDIDIKAN AGAMA HINDU",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MPK105",
        "NAMA_MK" => "PENDIDIKAN AGAMA BUDHA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM101",
        "NAMA_MK" => "LOGIKA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM111",
        "NAMA_MK" => "PENGANTAR SISTEM KOMPUTER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MPK102",
        "NAMA_MK" => "PENDD. AGAMA KRISTEN PROTESTAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "KBI101",
        "NAMA_MK" => "BAHASA INGGRIS",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MBB101",
        "NAMA_MK" => "ILMU SOSIAL DAN BUDAYA DASAR",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT110",
        "NAMA_MK" => "KALKULUS I",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "FIS105",
        "NAMA_MK" => "FISIKA DASAR",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "KBS101",
        "NAMA_MK" => "BAHASA INDONESIA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM100",
        "NAMA_MK" => "ALGORITMA",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM110",
        "NAMA_MK" => "ARSITEKTUR DAN ORG. KOMPUTER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT122",
        "NAMA_MK" => "ALJABAR LINEAR",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM120",
        "NAMA_MK" => "PEMROGRAMAN KOMPUTER I",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT222",
        "NAMA_MK" => "MATEMATIKA DISKRIT I",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT221",
        "NAMA_MK" => "ALJABAR LINIER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "KJR116",
        "NAMA_MK" => "OLAH RAGA",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT111",
        "NAMA_MK" => "KALKULUS II",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT130",
        "NAMA_MK" => "STATISTIKA DASAR",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MPK107",
        "NAMA_MK" => "KEWARGANEGARAAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT109",
        "NAMA_MK" => "ALJABAR LINEAR ELEMENTER",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM230",
        "NAMA_MK" => "STRUKTUR DATA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM222",
        "NAMA_MK" => "RANCANG BANGUN APLIKASI XBASE",
        "SKS" => "3",
        "SIFAT" => "PILIHAN WAJIB",
    ),
    array(
        "KODE" => "COM221",
        "NAMA_MK" => "PEMROGRAMAN KOMPUTER II",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM231",
        "NAMA_MK" => "TEKNOLOGI INFORMASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM212",
        "NAMA_MK" => "SISTEM OPERASI I",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM240",
        "NAMA_MK" => "KOMUNIKASI DATA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM202",
        "NAMA_MK" => "ANALISIS ALGORITMA",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT223",
        "NAMA_MK" => "MATEMATIKA DISKRIT II",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "MAT230",
        "NAMA_MK" => "PENGT. TEORI PELUANG",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM260",
        "NAMA_MK" => "PENGOLAHAN CITRA",
        "SKS" => "2",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM233",
        "NAMA_MK" => "SISTEM INFORMASI I",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM223",
        "NAMA_MK" => "PEMROGRAMAN BEORIENTASI OBYEK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM280",
        "NAMA_MK" => "SISTEM OPERASI II",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM241",
        "NAMA_MK" => "JARINGAN KOMPUTER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM281",
        "NAMA_MK" => "PEMROGRAMAN KOMPUTER III",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM232",
        "NAMA_MK" => "BASIS DATA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM213",
        "NAMA_MK" => "BAHASA ASSEMBLER",
        "SKS" => "3",
        "SIFAT" => "PILIHAN WAJIB",
    ),
    array(
        "KODE" => "COM261",
        "NAMA_MK" => "MULTIMEDIA",
        "SKS" => "3",
        "SIFAT" => "PILIHAN WAJIB",
    ),
    array(
        "KODE" => "MJN160",
        "NAMA_MK" => "PENGANTAR MANAJEMEN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM315",
        "NAMA_MK" => "MIKROPROSESOR",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "MAT333",
        "NAMA_MK" => "PENGANTAR STOKASTIK",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM342",
        "NAMA_MK" => "SISTEM KEAMANAN KOMPUTER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM334",
        "NAMA_MK" => "SISTEM INFORMASI II",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM314",
        "NAMA_MK" => "SISTEM DIGITAL",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT350",
        "NAMA_MK" => "METODE NUMERIK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MAT203",
        "NAMA_MK" => "RISET OPERASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM351",
        "NAMA_MK" => "HUKUM TELEMATIKA",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM324",
        "NAMA_MK" => "REKAYASA PERANGKAT LUNAK I",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM493",
        "NAMA_MK" => "METODOLOGI PENELITIAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM335",
        "NAMA_MK" => "DATA MINING",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM336",
        "NAMA_MK" => "MANAJEMEN SISTEM INFORMASI",
        "SKS" => "3",
        "SIFAT" => "PILIHAN WAJIB",
    ),
    array(
        "KODE" => "KOM101",
        "NAMA_MK" => "PENGANTAR ILMU KOMUNIKASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM316",
        "NAMA_MK" => "SISTEM INTERFACE",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM350",
        "NAMA_MK" => "INTERAKSI MANUSIA DAN KOMPUTER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM337",
        "NAMA_MK" => "MANAJEMEN PROYEK",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM452",
        "NAMA_MK" => "ETIKA PROFESI",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM427",
        "NAMA_MK" => "SISTEM WAKTU NYATA",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM403",
        "NAMA_MK" => "TEORI BAHASA DAN AUTOMATA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM494",
        "NAMA_MK" => "KAPITA SELEKTA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM438",
        "NAMA_MK" => "E-COMMERCE",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM425",
        "NAMA_MK" => "REKAYASA PERANGKAT LUNAK II",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM426",
        "NAMA_MK" => "PENGUJIAN PERANGKAT LUNAK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM470",
        "NAMA_MK" => "KECERDASAN BUATAN",
        "SKS" => "3",
        "SIFAT" => "PILIHAN WAJIB",
    ),
    array(
        "KODE" => "MJN270",
        "NAMA_MK" => "KEWIRAUSAHAAN",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM495",
        "NAMA_MK" => "KERJA PRAKTEK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM499",
        "NAMA_MK" => "SKRIPSI",
        "SKS" => "4",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI500",
        "NAMA_MK" => "KULIAH KERJA NYATA TEMATIK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM443",
        "NAMA_MK" => "GRAF DAN DESAIN JARINGAN",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM471",
        "NAMA_MK" => "JARINGAN SYARAF TIRUAN",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "COM472",
        "NAMA_MK" => "FUZZY LOGIC",
        "SKS" => "3",
        "SIFAT" => "PILIHAN BEBAS",
    ),
    array(
        "KODE" => "UNI400",
        "NAMA_MK" => "PEMBEKALAN KKN",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM497",
        "NAMA_MK" => "SEMINAR USUL PENELITIAN",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "COM498",
        "NAMA_MK" => "SEMINAR HASIL PENELITIAN",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
);
$kur_mi_2012 = array(
    array(
        "KODE" => "UNI512109",
        "NAMA_MK" => "MATEMATIKA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI512107",
        "NAMA_MK" => "PENDIDIKAN PANCASILA DAN KEWARGANEGARAAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI512106",
        "NAMA_MK" => "BAHASA INDONESIA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI512105",
        "NAMA_MK" => "PENDIDIKAN AGAMA BUDHA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI512103",
        "NAMA_MK" => "PENDIDIKAN AGAMA KRISTEN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI512102",
        "NAMA_MK" => "PENDIDIKAN AGAMA KATHOLIK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI512101",
        "NAMA_MK" => "PENDIDIKAN AGAMA ISLAM",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512103",
        "NAMA_MK" => "ALGORITMA DAN PEMROGRAMAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512101",
        "NAMA_MK" => "PENGANTAR MANAJEMEN ORGANISASI",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512102",
        "NAMA_MK" => "PENGANTAR TEKNOLOGI INFORMASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI612104",
        "NAMA_MK" => "PENDIDIKAN AGAMA HINDU",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI512110",
        "NAMA_MK" => "LOGIKA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512106",
        "NAMA_MK" => "ARSITEKTUR KOMPUTER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512104",
        "NAMA_MK" => "BAHASA INGGRIS UNTUK KOMPUTER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512105",
        "NAMA_MK" => "PENGANTAR AKUNTANSI",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512107",
        "NAMA_MK" => "PENGANTAR SISTEM INFORMASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512108",
        "NAMA_MK" => "STRUKTUR DATA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512109",
        "NAMA_MK" => "MULTIMEDIA DASAR",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512110",
        "NAMA_MK" => "PEMROGRAMAN TERSTRUKTUR",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI512121",
        "NAMA_MK" => "STATISTIKA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512205",
        "NAMA_MK" => "PEMROGRAMAN BERORIENTASI OBJEK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512206",
        "NAMA_MK" => "MULTIMEDIA LANJUT",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512207",
        "NAMA_MK" => "SISTEM OPERASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512201",
        "NAMA_MK" => "KOMUNIKASI DATA DAN JARINGAN INTERNET",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512202",
        "NAMA_MK" => "BASIS DATA",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512203",
        "NAMA_MK" => "DESAIN SISTEM INFORMASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512204",
        "NAMA_MK" => "PEMROGRAMAN DESKTOP",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512211",
        "NAMA_MK" => "PEMROGRMAN CLIENT SERVER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512212",
        "NAMA_MK" => "PEMROGRAMAN MOBILE",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512213",
        "NAMA_MK" => "REKAYASA PERANGKAT LUNAK",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512209",
        "NAMA_MK" => "KEAMANAN SISTEM INFORMASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512208",
        "NAMA_MK" => "INTERAKSI MANUSIA DAN KOMPUTER",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "UNI512206",
        "NAMA_MK" => "KEWIRAUSAHAAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512210",
        "NAMA_MK" => "PEMROGRAMAN BERBASIS WEB",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512302",
        "NAMA_MK" => "MANAJEMEN PROYEK SISTEM INFORMASI",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512303",
        "NAMA_MK" => "REKAYASA PERANGKAT LUNAK LANJUT",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIP512303",
        "NAMA_MK" => "ETIKA PROFESI",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512301",
        "NAMA_MK" => "TEKNIK PENULISAN KARYA ILMIAH",
        "SKS" => "2",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512306",
        "NAMA_MK" => "PEMROGRAMAN BERBASIS WEB LANJUT",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512305",
        "NAMA_MK" => "PEMROGRAMAN MOBILE LANJUT",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512304",
        "NAMA_MK" => "E-COMMERCE",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512307",
        "NAMA_MK" => "SEMINAR TUGAS AKHIR",
        "SKS" => "1",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIN512308",
        "NAMA_MK" => "TUGAS AKHIR",
        "SKS" => "4",
        "SIFAT" => "WAJIB",
    ),
    array(
        "KODE" => "MIP512302",
        "NAMA_MK" => "PRAKTIK KERJA LAPANGAN",
        "SKS" => "3",
        "SIFAT" => "WAJIB",
    ),
);
function array_to_xml($array, &$xml_kurikulum) {
    foreach($array as $key => $value) {
        if(is_array($value)) {
            if(!is_numeric($key)){
                $subnode = $xml_kurikulum->addChild("$key");
                array_to_xml($value, $subnode);
            }else{
                $subnode = $xml_kurikulum->addChild("MATAKULIAH");
                array_to_xml($value, $subnode);
            }
        }else {
            $xml_kurikulum->addChild("$key",htmlspecialchars("$value"));
        }
    }
}
$xml_kurikulum = new SimpleXMLElement("<?xml version=\"1.0\"?><kurkulum></kurkulum>");

//function call to convert array to xml
$kurikulum="kur_ilkom_2005";
array_to_xml($$kurikulum,$xml_kurikulum);

//saving generated xml file
$xml_file = $xml_kurikulum->asXML($kurikulum.'.xml');

//success and error message based on xml creation
if($xml_file){
    echo 'XML file have been generated successfully.';
}else{
    echo 'XML file generation error.';
}
?>